Repository jenkinsci/workflow-support-plugin, pull requests merged in 2021-12, with the labels that each got.

#130 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  CHANGELOG.md
  README.md
  pom.xml
Labels: internal

#131 bump jenkins version to 2.289.1
  pom.xml
Labels: dependencies

#117 Vendored Guava should not use reflection
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/ChainingListenableFuture.java
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/DirectExecutor.java
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/Futures.java
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/ListFuture.java
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/MoreExecutors.java
Labels: internal

#129 [JENKINS-67389] Use FileChannel to save program.dat to avoid corruption
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/RiverWriter.java
Labels: bug
