Repository jenkinsci/workflow-support-plugin, pull requests merged in 2021-11, with the labels that each got.

#122 `WorkspaceRunAction` optimization
  src/main/java/org/jenkinsci/plugins/workflow/support/actions/WorkspaceRunAction.java
Labels: enhancement

#121 Reduce usages of Guava
  src/main/java/org/jenkinsci/plugins/workflow/support/actions/LogActionImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/RiverReader.java
Labels: enhancement

#118 Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`
  src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ThrowablePickleTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/SerializationSecurityTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/RunWrapperTest.java
Labels: tests

#119 Update plugin POM and BOM
  pom.xml
Labels: dependencies

#124 Add Dependabot configuration
  .github/dependabot.yml
Labels: dependencies

#128 Allow icon overrides by modern Jenkins versions
  src/main/resources/org/jenkinsci/plugins/workflow/support/visualization/table/ConsoleColumn/column.jelly
  src/main/webapp/images/32x32/terminal.png
Labels: internal
