Repository jenkinsci/workflow-support-plugin, pull requests merged in 2024-03, with the labels that each got.

#255 Save `flowNodeStore.xml` entries in order
  src/main/java/org/jenkinsci/plugins/workflow/support/storage/BulkFlowNodeStorage.java
  src/test/java/org/jenkinsci/plugins/workflow/support/storage/BulkFlowNodeStorageTest.java
Labels: enhancement

#256 Miscellaneous code cleanup
  src/main/java/org/jenkinsci/plugins/workflow/support/DefaultStepContext.java
  src/main/java/org/jenkinsci/plugins/workflow/support/actions/LogActionImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/support/actions/PauseAction.java
  src/main/java/org/jenkinsci/plugins/workflow/support/actions/WorkspaceActionImpl.java
  src/main/java/org/jenkinsci/plugins/workflow/support/actions/WorkspaceRunAction.java
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/ChainingListenableFuture.java
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/Futures.java
  src/main/java/org/jenkinsci/plugins/workflow/support/concurrent/MoreExecutors.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/TryRepeatedly.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/PickleResolver.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/RiverReader.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/RiverWriter.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/POSTHyperlinkNote.java
  src/main/java/org/jenkinsci/plugins/workflow/support/storage/BulkFlowNodeStorage.java
  src/main/java/org/jenkinsci/plugins/workflow/support/storage/SimpleXStreamFlowNodeStorage.java
  src/main/java/org/jenkinsci/plugins/workflow/support/visualization/table/FlowGraphTable.java
  src/test/java/org/jenkinsci/plugins/workflow/support/actions/PauseActionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/EphemeralPickleResolverTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/pickles/serialization/RiverWriterTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/build/RunWrapperTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/storage/AbstractStorageTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/storage/MockFlowExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/storage/StorageTestUtils.java
Labels: internal

#258 Try to fix synchronization in `SemaphoreStep`
  src/test/java/org/jenkinsci/plugins/workflow/test/steps/SemaphoreStep.java
Labels: developer
