Repository jenkinsci/workflow-support-plugin, pull requests merged in 2025-01, with the labels that each got.

#290 Require 2.452.4
  pom.xml
Labels: dependencies

#295 Relaxing assertion in `FlowGraphTableTest`
  src/test/java/org/jenkinsci/plugins/workflow/support/visualization/table/FlowGraphTableTest.java
Labels: developer

#296 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/input/POSTHyperlinkNote.java
Labels: internal
